//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 04:26:38 PM BST 
//


package org.datacontract.schemas._2004._07.integrationservicelayer_services_entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GrossProfit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GrossProfit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="profit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="percentange" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GrossProfit", propOrder = {
    "profit",
    "percentange"
})
public class GrossProfit {

    protected int profit;
    protected int percentange;

    /**
     * Gets the value of the profit property.
     * 
     */
    public int getProfit() {
        return profit;
    }

    /**
     * Sets the value of the profit property.
     * 
     */
    public void setProfit(int value) {
        this.profit = value;
    }

    /**
     * Gets the value of the percentange property.
     * 
     */
    public int getPercentange() {
        return percentange;
    }

    /**
     * Sets the value of the percentange property.
     * 
     */
    public void setPercentange(int value) {
        this.percentange = value;
    }

}
