//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 04:26:38 PM BST 
//


package org.datacontract.schemas._2004._07.integrationservicelayer_services_entities;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.datacontract.schemas._2004._07.integrationservicelayer_services_entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.datacontract.schemas._2004._07.integrationservicelayer_services_entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VehicleValuationResponse }
     * 
     */
    public VehicleValuationResponse createVehicleValuationResponse() {
        return new VehicleValuationResponse();
    }

    /**
     * Create an instance of {@link Mileage }
     * 
     */
    public Mileage createMileage() {
        return new Mileage();
    }

    /**
     * Create an instance of {@link Valuation }
     * 
     */
    public Valuation createValuation() {
        return new Valuation();
    }

    /**
     * Create an instance of {@link Confidence }
     * 
     */
    public Confidence createConfidence() {
        return new Confidence();
    }

    /**
     * Create an instance of {@link VehicleValuationRequest }
     * 
     */
    public VehicleValuationRequest createVehicleValuationRequest() {
        return new VehicleValuationRequest();
    }

    /**
     * Create an instance of {@link GrossProfit }
     * 
     */
    public GrossProfit createGrossProfit() {
        return new GrossProfit();
    }

}
