//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 04:26:38 PM BST 
//


package org.datacontract.schemas._2004._07.integrationservicelayer_services_entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Valuation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Valuation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="retail" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="trade" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="supermarket" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="independent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="franchise" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="GrossProfit" type="{http://schemas.datacontract.org/2004/07/IntegrationServiceLayer.Services.Entities.CazanaVehicleValuationLookup}GrossProfit"/>
 *         &lt;element name="percentOfOcn" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="valuationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Valuation", propOrder = {
    "retail",
    "trade",
    "supermarket",
    "independent",
    "franchise",
    "grossProfit",
    "percentOfOcn",
    "valuationDate"
})
public class Valuation {

    protected int retail;
    protected int trade;
    protected int supermarket;
    protected int independent;
    protected int franchise;
    @XmlElement(name = "GrossProfit", required = true)
    protected GrossProfit grossProfit;
    protected double percentOfOcn;
    @XmlElement(required = true)
    protected String valuationDate;

    /**
     * Gets the value of the retail property.
     * 
     */
    public int getRetail() {
        return retail;
    }

    /**
     * Sets the value of the retail property.
     * 
     */
    public void setRetail(int value) {
        this.retail = value;
    }

    /**
     * Gets the value of the trade property.
     * 
     */
    public int getTrade() {
        return trade;
    }

    /**
     * Sets the value of the trade property.
     * 
     */
    public void setTrade(int value) {
        this.trade = value;
    }

    /**
     * Gets the value of the supermarket property.
     * 
     */
    public int getSupermarket() {
        return supermarket;
    }

    /**
     * Sets the value of the supermarket property.
     * 
     */
    public void setSupermarket(int value) {
        this.supermarket = value;
    }

    /**
     * Gets the value of the independent property.
     * 
     */
    public int getIndependent() {
        return independent;
    }

    /**
     * Sets the value of the independent property.
     * 
     */
    public void setIndependent(int value) {
        this.independent = value;
    }

    /**
     * Gets the value of the franchise property.
     * 
     */
    public int getFranchise() {
        return franchise;
    }

    /**
     * Sets the value of the franchise property.
     * 
     */
    public void setFranchise(int value) {
        this.franchise = value;
    }

    /**
     * Gets the value of the grossProfit property.
     * 
     * @return
     *     possible object is
     *     {@link GrossProfit }
     *     
     */
    public GrossProfit getGrossProfit() {
        return grossProfit;
    }

    /**
     * Sets the value of the grossProfit property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrossProfit }
     *     
     */
    public void setGrossProfit(GrossProfit value) {
        this.grossProfit = value;
    }

    /**
     * Gets the value of the percentOfOcn property.
     * 
     */
    public double getPercentOfOcn() {
        return percentOfOcn;
    }

    /**
     * Sets the value of the percentOfOcn property.
     * 
     */
    public void setPercentOfOcn(double value) {
        this.percentOfOcn = value;
    }

    /**
     * Gets the value of the valuationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuationDate() {
        return valuationDate;
    }

    /**
     * Sets the value of the valuationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuationDate(String value) {
        this.valuationDate = value;
    }

}
