//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 04:26:38 PM BST 
//


package org.datacontract.schemas._2004._07.integrationservicelayer_services_entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="make" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ocn" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daysToSale" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Mileage" type="{http://schemas.datacontract.org/2004/07/IntegrationServiceLayer.Services.Entities.CazanaVehicleValuationLookup}Mileage"/>
 *         &lt;element name="youngUsed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Valuation" type="{http://schemas.datacontract.org/2004/07/IntegrationServiceLayer.Services.Entities.CazanaVehicleValuationLookup}Valuation"/>
 *         &lt;element name="stockingDepreciation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Confidence" type="{http://schemas.datacontract.org/2004/07/IntegrationServiceLayer.Services.Entities.CazanaVehicleValuationLookup}Confidence"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cid",
    "make",
    "model",
    "ocn",
    "daysToSale",
    "mileage",
    "youngUsed",
    "valuation",
    "stockingDepreciation",
    "confidence"
})
@XmlRootElement(name = "VehicleValuationResponse")
public class VehicleValuationResponse {

    protected int cid;
    @XmlElement(required = true)
    protected String make;
    @XmlElement(required = true)
    protected String model;
    protected int ocn;
    protected int daysToSale;
    @XmlElement(name = "Mileage", required = true)
    protected Mileage mileage;
    protected int youngUsed;
    @XmlElement(name = "Valuation", required = true)
    protected Valuation valuation;
    @XmlElement(required = true)
    protected String stockingDepreciation;
    @XmlElement(name = "Confidence", required = true)
    protected Confidence confidence;

    /**
     * Gets the value of the cid property.
     * 
     */
    public int getCid() {
        return cid;
    }

    /**
     * Sets the value of the cid property.
     * 
     */
    public void setCid(int value) {
        this.cid = value;
    }

    /**
     * Gets the value of the make property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMake() {
        return make;
    }

    /**
     * Sets the value of the make property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMake(String value) {
        this.make = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the ocn property.
     * 
     */
    public int getOcn() {
        return ocn;
    }

    /**
     * Sets the value of the ocn property.
     * 
     */
    public void setOcn(int value) {
        this.ocn = value;
    }

    /**
     * Gets the value of the daysToSale property.
     * 
     */
    public int getDaysToSale() {
        return daysToSale;
    }

    /**
     * Sets the value of the daysToSale property.
     * 
     */
    public void setDaysToSale(int value) {
        this.daysToSale = value;
    }

    /**
     * Gets the value of the mileage property.
     * 
     * @return
     *     possible object is
     *     {@link Mileage }
     *     
     */
    public Mileage getMileage() {
        return mileage;
    }

    /**
     * Sets the value of the mileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mileage }
     *     
     */
    public void setMileage(Mileage value) {
        this.mileage = value;
    }

    /**
     * Gets the value of the youngUsed property.
     * 
     */
    public int getYoungUsed() {
        return youngUsed;
    }

    /**
     * Sets the value of the youngUsed property.
     * 
     */
    public void setYoungUsed(int value) {
        this.youngUsed = value;
    }

    /**
     * Gets the value of the valuation property.
     * 
     * @return
     *     possible object is
     *     {@link Valuation }
     *     
     */
    public Valuation getValuation() {
        return valuation;
    }

    /**
     * Sets the value of the valuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Valuation }
     *     
     */
    public void setValuation(Valuation value) {
        this.valuation = value;
    }

    /**
     * Gets the value of the stockingDepreciation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockingDepreciation() {
        return stockingDepreciation;
    }

    /**
     * Sets the value of the stockingDepreciation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockingDepreciation(String value) {
        this.stockingDepreciation = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Confidence }
     *     
     */
    public Confidence getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Confidence }
     *     
     */
    public void setConfidence(Confidence value) {
        this.confidence = value;
    }

}
